"""add categories table and link to courses

Revision ID: 53625e49a6e5
Revises: a57925a666ad
Create Date: 2026-04-18 21:23:06.443146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53625e49a6e5'
down_revision: Union[str, Sequence[str], None] = 'a57925a666ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('courses', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'courses', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', name='lesson_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
