"""add cover_url to courses

Revision ID: a57925a666ad
Revises: e8e940a4a7f2
Create Date: 2026-04-18 17:46:52.443215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57925a666ad'
down_revision: Union[str, Sequence[str], None] = 'e8e940a4a7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('cover_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', name='lesson_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('courses', 'cover_url')
    # ### end Alembic commands ###
