"""add avatar_url to users

Revision ID: e8e940a4a7f2
Revises: 73821bc13e97
Create Date: 2026-04-18 17:18:16.623809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e940a4a7f2'
down_revision: Union[str, Sequence[str], None] = '73821bc13e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.alter_column('lessons', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', name='lesson_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
